include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
    sort_child_properties_last: false
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    file_names: true

analyzer:
  errors:
    # unused_import: error
    # unused_local_variable: error
    always_declare_return_types: error
    file_names: error
    avoid_unnecessary_containers: error
